ding:
  demo:
    appKey: "??"
    appSecret: "??"
    corpId: "??"
    dingAccessToken: "https://oapi.dingtalk.com/gettoken?appkey={appkey}&appsecret={appsecret}"
    dingGetUserId: "https://oapi.dingtalk.com/user/getuserinfo?access_token={access_token}&code={code}"
    dingGetUser: "https://oapi.dingtalk.com/user/get?access_token={access_token}&userid={userid}"
server:
  port: 9001